name: nfcore-exoseq
dependencies:
  - conda-forge::openjdk # Needed for FastQC docker - see bioconda/bioconda-recipes#5026
  - bwa=0.7.17
  - fastqc=0.11.5
  - trim-galore=0.4.5
  - samtools=1.7
  - gatk4=4.0.2.0
  - qualimap=2.2.2a
  - multiqc=1.5a
channels:
  - conda-forge
  - bioconda
